Fixes #110 Built the library from skycoin / lib skycoin
skycoin/pyskycoin pull request #121
Opened 2019-02-10 04:52 UTC by stdevHan

Fixes #110 

Changes:
- Submodule change skycoin/skycoin => skycoin/libskycoin@develop
- Changes in url declarations for skycoin/skycoin => skycoin/libskycoin

Does this change need to mentioned in CHANGELOG.md?

Yes

2019-02-10 18:33 UTC, olemis requested changes

2019-02-10 18:33 UTC, olemis commented on .gitmodules
> +[submodule "gopath/src/github.com/skycoin/libskycoin"]
add submodule just once

2019-02-10 18:56 UTC, olemis requested changes

2019-02-10 18:56 UTC, olemis commented on Makefile
> +	swig -python -w501,505,401,302,509,451 -Iswig/include -I$(INCLUDE_DIR) -I$(SKYCOIN_DIR)/include -outdir ./skycoin/ -o swig/pyskycoin_wrap.c $(LIBSWIG_DIR)/pyskycoin.i
`INCLUDE_DIR = $SKYCOIN_DIR/include`

2019-02-10 19:08 UTC, olemis requested changes

2019-02-10 19:08 UTC, olemis commented on .travis.yml
> +- make test
as before

2019-02-10 20:15 UTC, stdevHan commented on .gitmodules
> +[submodule "gopath/src/github.com/skycoin/libskycoin"]
ok, thnx

2019-02-10 20:21 UTC, olemis commented on tests/test_cipher_address.py
> -def test_TestDecodeBase58Address():
why ? how are them addresses checked for validity ?

2019-02-10 20:33 UTC, olemis requested changes

2019-02-10 20:33 UTC, olemis commented on tests/test_cipher_address.py
> -def test_TestDecodeBase58Address():
`skycoin/skycoin` is using an exdternal library for `base58` . Please implement this according to this . This function is essential . Needs testing .

2019-02-10 20:45 UTC, olemis commented
Another branch +PR is needed to implement this against `v0.25.1` .

2019-04-30 21:03 UTC, stdevHan commented on tests/test_cipher_address.py
> -def test_TestDecodeBase58Address():
I'll just comment, since 0.25.1 is enabled that function

2019-04-30 21:03 UTC, stdevHan commented on .gitmodules
> +[submodule "gopath/src/github.com/skycoin/libskycoin"]
ok, thnx

2023-10-10 10:13 UTC, closed without merging